import {it,expect} from 'vitest';
import {chromium} from '@playwright/test';
import {createServer} from 'node:http';
import {runWorkflow} from './index.js';
import type {Workflow} from '@web-agent/protocol';
const target={fingerprint:{tag:'input'},locators:[{strategy:'css' as const,value:'#account',score:1}]};
async function fixture(){let contacted=0;const dest=createServer((_q,r)=>{contacted++;r.writeHead(200,{'Content-Type':'text/html; charset=utf-8'}).end('<input id="account"><p id="result">destination</p>')});await new Promise<void>(r=>dest.listen(0,'127.0.0.1',r));const destination=`http://127.0.0.1:${(dest.address() as any).port}`;let origin='';const source=createServer((q,r)=>{if(q.url==='/redirect')return r.writeHead(302,{location:destination}).end();if(q.url==='/multi')return r.writeHead(302,{location:origin+'/redirect'}).end();r.writeHead(200,{'Content-Type':'text/html; charset=utf-8'}).end(`<input id="account"><a href="${destination}">查询</a><a target="_blank" href="${destination}">查询新标签</a>`)});await new Promise<void>(r=>source.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${(source.address() as any).port}`;return {origin,destination,contacted:()=>contacted,close:async()=>{for(const s of[source,dest])await new Promise<void>(r=>{s.close(()=>r());s.closeAllConnections()})}}}
function workflow(startUrl:string,steps:Workflow['steps']):Workflow{return {schemaVersion:'1.0',id:'origin',version:1,name:'origin',startUrl,variables:{},steps,metadata:{createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}}
it.each(['start','redirect','multi','link','popup'])('blocks %s origin escape before destination receives a request or later actions execute',async mode=>{const f=await fixture();const browser=await chromium.launch({headless:true});try{const page=await browser.newPage({serviceWorkers:'block'});const first:Workflow['steps']=mode==='start'?[]:mode==='link'||mode==='popup'?[{id:'link',type:'click',target:{fingerprint:{tag:'a'},locators:[{strategy:'text',value:mode==='link'?'查询':'查询新标签',score:1}]}}]:[{id:'nav',type:'navigate',url:f.origin+'/'+mode}];const result=await runWorkflow(page,workflow(f.origin+(mode==='start'?'/redirect':''),[...first,{id:'input',type:'input',target,parameters:{value:'10001'}},{id:'extract',type:'extract',target,parameters:{operation:'extractCount',key:'count'}},{id:'assert',type:'assert',parameters:{assertions:[]}}]));expect(result.status).toBe('blocked');expect(f.contacted()).toBe(0);expect(result.steps.some(s=>s.id==='input'&&s.status==='completed')).toBe(false);expect(result.outputs).toEqual({});}finally{await browser.close();await f.close()}},15000);
it('retains same-origin and explicitly allowlisted redirects',async()=>{const f=await fixture();const browser=await chromium.launch({headless:true});try{const page=await browser.newPage({serviceWorkers:'block'});expect((await runWorkflow(page,workflow(f.origin,[{id:'input',type:'input',target,parameters:{value:'10001'}}]))).status).toBe('success');expect((await runWorkflow(page,workflow(f.origin,[{id:'nav',type:'navigate',url:f.origin+'/multi'},{id:'input',type:'input',target,parameters:{value:'10001'}}]),{policy:{mode:'read-only',allowedOrigins:[f.destination]}})).status).toBe('success');expect(await page.locator('#account').inputValue()).toBe('10001');}finally{await browser.close();await f.close()}},15000);
it('rejects an existing HTTP Service Worker before workflow navigation',async()=>{
 const server=createServer((q,r)=>q.url==='/sw.js'?r.writeHead(200,{'Content-Type':'application/javascript'}).end("self.addEventListener('install',()=>self.skipWaiting());self.addEventListener('activate',e=>e.waitUntil(clients.claim()));"):r.writeHead(200,{'Content-Type':'text/html'}).end('worker fixture'));
 await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${(server.address() as any).port}`;const browser=await chromium.launch({headless:true});try{const page=await browser.newPage();await page.goto(origin);await page.evaluate(async()=>{await navigator.serviceWorker.register('/sw.js');await navigator.serviceWorker.ready;});const result=await runWorkflow(page,workflow(origin,[{id:'input',type:'input',target,parameters:{value:'10001'}}]));expect(result.status).toBe('blocked');expect(result.steps).toHaveLength(1);expect(result.steps[0].message).toContain('Service Worker');}finally{await browser.close();await new Promise<void>(r=>{server.close(()=>r());server.closeAllConnections()})}
},15000);it('accepts a same-origin child document while its initial frame navigation commits',async()=>{
 const server=createServer((q,r)=>r.writeHead(200,{'Content-Type':'text/html'}).end(q.url==='/child'?'<p>child</p>':'<input id="account"><iframe src="/child"></iframe>'));
 await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${(server.address() as any).port}`;const browser=await chromium.launch({headless:true});try{const page=await browser.newPage();const result=await runWorkflow(page,workflow(origin,[{id:'input',type:'input',target,parameters:{value:'10001'}}]));expect(result.status,JSON.stringify(result)).toBe('success');expect(await page.locator('#account').inputValue()).toBe('10001');}finally{await browser.close();await new Promise<void>(r=>{server.close(()=>r());server.closeAllConnections()})}
},15000);
it('permits a same-origin popup but rejects its early redirect before contacting an unallowlisted destination',async()=>{
 let hits=0;const dest=createServer((_q,r)=>{hits++;r.end('escape')});await new Promise<void>(r=>dest.listen(0,'127.0.0.1',r));const destination=`http://127.0.0.1:${(dest.address() as any).port}`;const server=createServer((q,r)=>q.url==='/redirect'?r.writeHead(302,{location:destination}).end():r.writeHead(200,{'Content-Type':'text/html; charset=utf-8'}).end(q.url==='/child'?'<p>child</p>':`<a target="_blank" rel="opener" href="${q.url==='/escape'?'/redirect':'/child'}">查询新标签</a>`));await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${(server.address() as any).port}`;const browser=await chromium.launch();try{const step:Workflow['steps']=[{id:'popup',type:'click',target:{fingerprint:{tag:'a'},locators:[{strategy:'text',value:'查询新标签',score:1}]}}];const p=await browser.newPage();expect((await runWorkflow(p,workflow(origin,step))).status).toBe('success');const q=await browser.newPage();expect((await runWorkflow(q,workflow(origin+'/escape',step))).status).toBe('blocked');expect(hits).toBe(0);}finally{await browser.close();for(const s of[server,dest])await new Promise<void>(r=>{s.close(()=>r());s.closeAllConnections()})}
},15000);
