import { test, expect, chromium } from '@playwright/test';
import { mkdir, readFile, readdir, writeFile, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { startFixtureServer } from '@web-agent/fixture-site';
import { parseWorkflow } from '@web-agent/protocol';
import { runWorkflow } from '@web-agent/runner';
import * as service from '../apps/recording-service/src/index.js';

test('visible Extension demonstration automatically produces a replayable versioned workflow', async ({}, info) => {
  expect(service).toHaveProperty('startRecordingService');
  console.info('UI E2E: starting local fixture and recording service');
  const root = info.outputPath('generated');
  await mkdir(root, { recursive: true });
  const fixture = await startFixtureServer();
  const bridge = await service.startRecordingService({ root });
  const profile = await mkdtemp(join(tmpdir(), 'record-to-workflow-'));
  const extension = resolve('apps/extension/dist');
  console.info('UI E2E: launching isolated Chromium with Extension');
  const context = await chromium.launchPersistentContext(profile, { channel: 'chromium', headless: true,
    args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`] });
  context.setDefaultTimeout(5000);
  try {
    console.info('UI E2E: opening Recorder UI');
    const page = await context.newPage();
    await page.goto(`${fixture.baseUrl}/rta`);
    const ui = page.locator('web-agent-recorder');
    await ui.locator('summary').click();
    await ui.locator('#generate-workflow').check();
    await expect(ui.locator('#capability')).toHaveCount(0);
    const worker = context.serviceWorkers()[0] ?? await context.waitForEvent('serviceworker');
    const popup = await context.newPage();
    await popup.goto(`chrome-extension://${new URL(worker.url()).host}/popup.html`);
    await popup.getByLabel('目标页面', { exact: true }).selectOption({ label: `${fixture.baseUrl}/rta` });
    await popup.getByLabel('本地服务地址', { exact: true }).fill(bridge.baseUrl);
    await popup.getByLabel('配对码', { exact: true }).fill(bridge.capability);
    await popup.getByRole('button', { name: '连接保存服务', exact: true }).click();
    await expect(popup.getByRole('status')).toHaveText('保存服务：已连接');
    await popup.close();
    await page.bringToFront();
    console.info('UI E2E: paired, recording user demonstration');
    await ui.getByRole('button', { name: '开始录制', exact: true }).click();
    await expect(ui.getByTestId('recording')).toHaveText('Recording: ON');
    await page.getByLabel('账户ID', { exact: true }).fill('10001');
    await page.getByRole('button', { name: '查询', exact: true }).click();
    await expect(page.locator('#query-result')).toContainText('10001');
    console.info('UI E2E: query result visible');
    await ui.getByLabel('变量名', { exact: true }).fill('accountId');
    await ui.getByRole('button', { name: '标记变量', exact: true }).click();
    await page.getByLabel('账户ID', { exact: true }).click();
    await expect(ui.getByTestId('annotations')).toHaveText('Annotations: 1');
    console.info('UI E2E: variable annotated');
    await ui.getByRole('button', { name: '标记提取', exact: true }).click();
    await page.locator('table').click();
    await expect(ui.getByTestId('annotations')).toHaveText('Annotations: 2');
    console.info('UI E2E: extraction annotated');
    await ui.getByLabel('断言类型', { exact: true }).selectOption('assertText');
    await ui.getByLabel('预期值', { exact: true }).fill('{{accountId}}');
    await ui.getByRole('button', { name: '标记断言', exact: true }).click();
    await page.locator('#query-result').click();
    await expect(ui.getByTestId('annotations')).toHaveText('Annotations: 3');
    console.info('UI E2E: stopping through UI and waiting for saved workflow');
    await ui.getByRole('button', { name: '停止录制', exact: true }).click();
    await expect(ui.getByTestId('saved')).toContainText('已保存：');
    await expect(ui.getByTestId('recording')).toHaveText('Recording: OFF');
    await page.screenshot({ path: info.outputPath('recorder.png') });
    const ids = await readdir(join(root, 'workflows'));
    expect(ids).toHaveLength(1);
    const path = join(root, 'workflows', ids[0], 'v1.json');
    const json = await readFile(path, 'utf8');
    const workflow = parseWorkflow(JSON.parse(json));
    const recording = join(root, 'data/recordings', workflow.metadata.sourceSessionId!);
    const raw = (await readFile(join(recording, 'raw-events.ndjson'), 'utf8')).trim().split('\n').map(line => JSON.parse(line));
    expect(raw[0].type).toBe('navigation');
    expect(JSON.parse(await readFile(join(recording, 'annotations.json'), 'utf8'))).toHaveLength(3);
    expect(JSON.parse(await readFile(join(recording, 'normalized-actions.json'), 'utf8')).some((action: { type: string }) => action.type === 'input')).toBe(true);
    expect(json).not.toContain('10001');
    expect(json).toContain('{{accountId}}');
    expect(json).not.toContain(bridge.capability);
    expect(workflow.steps.some(step => step.type === 'extract')).toBe(true);
    expect(workflow.steps.some(step => step.type === 'assert')).toBe(true);
    const runPage = await context.newPage();
    console.info('UI E2E: replaying generated workflow');
    const result = await runWorkflow(runPage, workflow, { variables: { accountId: '10001' } });
    expect(result.status, JSON.stringify(result)).toBe('success');
    expect(result.outputs.results).toMatchObject({ headers: ['策略ID', '策略名称', '状态'], rows: expect.arrayContaining([expect.arrayContaining(['账户 10001 策略 001'])]) });
    const second = await runWorkflow(runPage, workflow, { variables: { accountId: '20002' } });
    expect(second.status, JSON.stringify(second)).toBe('success');
    await expect(runPage.locator('#query-result')).toContainText('20002');
    await runPage.route('**/rta', async route => {
      const response = await route.fetch();
      await route.fulfill({ response, body: (await response.text()).replace(/result\.textContent = [^;]+;/, 'result.textContent = "无结果";') });
    });
    const failed = await runWorkflow(runPage, workflow, { variables: { accountId: '10001' } });
    expect(failed.status).toBe('failed');
    expect(failed.steps.at(-1)?.message).toBe('Required assertions failed');
    await writeFile(info.outputPath('run-results.json'), JSON.stringify({ result, second, failed }, null, 2));
  } finally { await context.close(); await bridge.close(); await fixture.close(); await rm(profile, { recursive: true, force: true }); }
});
